name = "syft"
type = "cli"

[resolve]
git-url = "https://github.com/anchore/syft"

[platform.linux]
download-file = "syft_{version}_linux_{arch}.tar.gz"
checksum-url = "syft_{version}_checksums.txt"
exe-path = "syft"

[platform.macos]
download-file = "syft_{version}_darwin_{arch}.tar.gz"
checksum-url = "syft_{version}_checksums.txt"
exe-path = "syft"

[install]
download-url = "https://github.com/anchore/syft/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
