name = "ast-grep"
type = "cli"

[resolve]
git-url = "https://github.com/ast-grep/ast-grep"

[platform.linux]
download-file = "app-{arch}-unknown-linux-gnu.zip"
exe-path = "ast-grep"

[platform.macos]
download-file = "app-{arch}-apple-darwin.zip"
exe-path = "ast-grep"

[platform.windows]
download-file = "app-{arch}-pc-windows-msvc.zip"
exe-path = "ast-grep.exe"

[install]
download-url = "https://github.com/ast-grep/ast-grep/releases/download/{version}/{download_file}"
