name = "pluto"
type = "cli"

[resolve]
git-url = "https://github.com/FairwindsOps/pluto"


[platform.linux]
download-file = "pluto_{version}_linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "pluto_{version}_darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "pluto_{version}_windows_{arch}.tar.gz"
checksum-file = "checksums.txt"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install]
download-url = "https://github.com/FairwindsOps/pluto/releases/download/v{version}/{download_file}"
